export const POST = {
  LOGIN: "common/auth/login",
  USER_UPDATE: "/users/update",
  HELP_DESK_SUPPORT: "/support/create",
  CHANGE_PASSWORD: "/users/change-password",
  SEND_OTP: "common/auth/send-otp",
  VERIFY_OTP: "common/auth/verify-otp",
  CREATE_DASHBOARD: "/dashboard/create",
  UPDATE_DASHBOARD: "/dashboard/update",
  DELETE_DASHBOARD: "/dashboard/delete",
  CREATE_WIDGET: "/dashboard/widget/create",
  UPDATE_WIDGET: "/dashboard/widget/update",
  DELETE_WIDGET: "/dashboard/widget/delete",
  SAVE_WIDGETS: "/dashboard/widget/save",
  CREATE_USER: "common/auth/create-user",
  UPDATE_USER: "/common/users/update/",
  DELETE_USER: "/common/users/delete/",
  ORGANIZATION_ACTIVE: "/organizations/updateStatus/",
  USER_ACTIVE: "/users/updateStatus/",
  FILE_UPLOAD: "/files/upload",
  CREATE_ENTITY: "/entities/create",
  UPDATE_ENTITY: "/entities/update",
  CREATE_ATTRIBUTE_OPTION: "/attributeOptions/create",
  CREATE_DATA_SOURCE: "/dataSource/create",
  Custom_Report: "/customReports",
  DATA_SOURCE_VERSION_CREATE: "/dataSourceVersion/create",
  CREATE_THEME: "/widgetTheme/create",
  DELETE_THEME: "/widgetTheme/delete/",
  DUPLICATE_THEME: "/widgetTheme/duplicate/",
  UPDATE_THEME: "/widgetTheme/update/",
  UPDATE_REPORT_SETTINGS: "/customReports/updateSettings",
  PERMISSION_CREATE: "/common/permission/create",
  Create_Organization: "/common/organization/create",
};

export const PUT = {
  UPDATE_DATA_SOURCE: "/dataSource/update",
  UPDATE_ATTRIBUTE_OPTION: "/attributeOptions/update",
  PERMISSION_UPDATE: "/common/permission/update",

  UPDATE_ORGANIZATION: "/common/organization/update/",
};

export const GET = {
  USER_DETAILS: "/common/user/get-current-user",
  USER_LIST: "/common/users/list",
  GET_USER: "/common/users/",
  GET_ORGANIZATION: "/organizations/",
  Entity_List: "/entities/list",
  Get_Entity: "/entities",
  Get_Entity_By_Id: "/entities:entityId",
  Attribute_Option_List: "attributeOptions/list",
  Attribute_Option_Get: "attributeOptions/get",
  Data_Source_List: "/common/dataSource/list",
  Data_Source_Code: "/common/dataSource/code",
  Data_Source_Version: "/common/dataSourceVersion",
  Data_Source: "/dataSource/dataSourceId",
  Data_Source_Name: "/dataSource/name",
  Data_Import_Error: "dataImportError",
  Custom_Report: "/customReports",
  DATA_SOURCE_LIST: "/common/dataSource/list",
  ATTRIBUTE_OPTIONS_LIST: "/attributeOptions/get/",
  SOURCE_VERSION_DATA: "/dataSourceVersion/versionData",
  DASHBOARD_LIST: "/common/dashboard/list",
  WIDGET_TYPE_LIST: "/widgetType/list",
  DASHBOARD_WIDGET_GET_CHART_DATA: "/dashboard/widget/getWidgets",
  DASHBOARD_WIDGET: "/dashboard/widget",
  DASHBOARD_WIDGET_DATA: "/dashboard/widget/getWidgetData",
  OPERATOR_LIST: "/operator/list",
  WIDGET_THEME: "/widgetTheme",
  NL_Query: "/nlQuery",
  NL_Query_INSIGHTS: "/nlQuery/insights",
  Report_Settings: "/common/customReports/listSettings?paginate=true",
  PERMISSION_List: "/common/permission/list",
  Organization_List: "/common/organization/list",
  Product_List: "/common/product/list",
  Product_Subscription_List: "/common/product-subscription/list",
};

export const DELETE = {
  PERMISSION_DELETE: "/common/permission/delete",
  Delete_Organization: "/common/organization/delete",
};
