// export const POST = {
//   LOGIN: 'common/auth/login',
//   USER_UPDATE: '/users/update',
//   HELP_DESK_SUPPORT: '/support/create',
//   CHANGE_PASSWORD: '/users/change-password',
//   SEND_OTP: 'common/auth/send-otp',
//   VERIFY_OTP: 'common/auth/verify-otp',
//   CREATE_DASHBOARD: '/common/dashboard/create',
//   UPDATE_DASHBOARD: '/common/dashboard/update',
//   DELETE_DASHBOARD: '/common/dashboard/delete',
//   CREATE_WIDGET: '/common/dashboard/widget/create',
//   UPDATE_WIDGET: '/common/dashboard/widget/update',
//   DELETE_WIDGET: '/common/dashboard/widget/delete',
//   SAVE_WIDGETS: '/common/dashboard/widget/save',
//   CREATE_USER: 'common/auth/create-user',
//   UPDATE_USER: '/common/users/update/',
//   DELETE_USER: '/common/users/delete/',
//   ORGANIZATION_ACTIVE: '/organizations/updateStatus/',
//   USER_ACTIVE: '/users/updateStatus/',
//   FILE_UPLOAD: '/common/files/upload',
//   CREATE_ENTITY: '/common/entities/create',
//   UPDATE_ENTITY: '/common/entities/update',
//   CREATE_ATTRIBUTE_OPTION: '/common/attributeOptions/create',
//   CREATE_DATA_SOURCE: '/common/dataSource/create',
//   Custom_Report: '/customReports',
//   DATA_SOURCE_VERSION_CREATE: '/dataSourceVersion/create',
//   CREATE_THEME: '/common/widgetTheme/create',
//   DELETE_THEME: '/widgetTheme/delete/',
//   DUPLICATE_THEME: '/widgetTheme/duplicate/',
//   UPDATE_THEME: '/widgetTheme/update/',
//   UPDATE_REPORT_SETTINGS: '/customReports/updateSettings',
//   Create_Organization: '/common/organization/create',
//   Create_User: '/common/user/create',
//   CREATE_PERMISSION: '/common/permission/create',
//   CREATE_ROLE: '/common/role/create',
//   CREATE_NOTIVIX_DASHBOARD: '/common/dashboard/create',
//   UPDATE_NOTIVIX_DASHBOARD: '/common/dashboard/update',
//   DELETE_NOTIVIX_DASHBOARD: '/common/dashboard/delete',
//   NOTIVIX_DASHBOARD_WIDGET: '/dashboard/widget',
//   NOTIVIX_DASHBOARD_THEME: '/dashboard/theme',
//   OPERATOR_LIST: '/common/operator/list',
//   CREATE_NOTIFICATION_TYPE: '/notivix/notification-setting/type/create',
//   CREATE_FREQUENCY: '/notivix/notification-setting/frequency/create',
//   CREATE_MEDIUM: '/notivix/notification-setting/medium/create',
//   CREATE_VERSION_ROW: '/common/dataSourceVersion/versionData/create',
//   RESOLVE_DATA_IMPORT_ERROR: '/common/dataImportError/resolve',
// };

// export const PUT = {
//   UPDATE_DATA_SOURCE: '/common/dataSource/update',
//   UPDATE_ATTRIBUTE_OPTION: '/common/attributeOptions/update',
//   UPDATE_ORGANIZATION: '/common/organization/update/',
//   UPDATE_USER: '/common/user/update/',
//   UPDATE_PERMISSION: '/common/permission/update',
//   UPDATE_ROLE: '/common/role/update',
//   UPDATE_MEDIUM: '/notivix/notification-setting/medium/update',
//   UPDATE_FREQUENCY: 'notivix/notification-setting/frequency/update',
//   UPDATE_NOTIFICATION_TYPE: 'notivix/notification-setting/type/update',
//   UPDATE_VERSION_ROW: '/common/dataSourceVersion/versionData/update',
//   SEND_ACKNOWLEDGE:"/notification-acknowledge/sendAcknowledge"
// };

// export const DELETE = {
//   Delete_Organization: '/common/organization/delete',
//   Delete_User: '/common/user/delete',
//   DELETE_PERMISSION: '/common/permission/delete',
//   DELETE_ROLE: '/common/role/delete',
//   DELETE_NOTIFICATION_TYPE: 'notivix/notification-setting/type/delete',
//   DELETE_MEDIUM: '/notivix/notification-setting/medium/delete',
//   DELETE_FREQUENCY: '/notivix/notification-setting/frequency/delete',
//   DELETE_VERSION_ROW: '/common/dataSourceVersion/versionData/delete',
// };

// export const GET = {
//   USER_DETAILS: '/common/user/get-current-user',
//   USER_LIST: '/common/users/list',
//   GET_USER: '/common/users/',
//   GET_ORGANIZATION: '/organizations/',
//   Entity_List: '/common/entities/list',
//   Get_Entity: '/common/entities',
//   Get_Entity_By_Id: 'common/entities',
//   Attribute_Option_List: '/common/attributeOptions/list',
//   Attribute_Option_Get: '/common/attributeOptions/get',
//   Data_Source_List: '/common/dataSource/list',
//   Data_Source_Code: '/common/dataSource/code',
//   Data_Source_Version: '/common/dataSourceVersion',
//   Data_Source: '/common/dataSource/dataSourceId',
//   Data_Source_Name: '/common/dataSource/name',
//   Data_Import_Error: '/common/dataImportError',
//   Custom_Report: '/reportivix/customReports',
//   DATA_SOURCE_LIST: '/common/dataSource/list',
//   ATTRIBUTE_OPTIONS_LIST: '/common/attributeOptions/get/',
//   SOURCE_VERSION_DATA: 'common/dataSourceVersion/versionData',
//   DASHBOARD_LIST: '/common/dashboard/list',
//   WIDGET_TYPE_LIST: '/common/widgetType/list',
//   DASHBOARD_WIDGET_GET_CHART_DATA: '/common/dashboard/widget/getWidgets',
//   DASHBOARD_WIDGET: '/dashboard/widget',
//   DASHBOARD_WIDGET_DATA: '/common/dashboard/widget/getWidgetData',
//   FIXED_DASHBOARD_WIDGET_DATA: '/common/dataSourceVersion/chartData',
//   OPERATOR_LIST: '/common/operator/list',
//   WIDGET_THEME: '/common/widgetTheme',
//   NL_Query: '/nlQuery',
//   NL_Query_INSIGHTS: '/nlQuery/insights',
//   Report_Settings: '/common/customReports/listSettings?paginate=true',
//   Organization_List: '/common/organization/list',
//   Product_List: '/common/product/list',
//   Product_Subscription_List: '/common/product-subscription/list',
//   User_List: '/common/user/list',
//   Roles_List: '/common/role/list',
//   PERMISSION_LIST: '/common/permission/list',
//   ROLE_LIST: '/common/role/list',
//   ROLE_DETAIL: '/common/role',
//   NOTIVIX_DASHBOARD_LIST: '/common/dashboard/list',
//   NOTIVIX_DASHBOARD_WIDGET_GET_CHART_DATA: '/common/dashboard/widget/getWidgets',
//   NOTIVIX_DASHBOARD_WIDGET_DATA: '/common/dashboard/widget/getWidgetData',
//   NOTIFICATION_TYPE_LIST: '/notivix/notification-setting/type/list',
//   TEMPLATE_LIST: '/notivix/notification-setting/template/list',
//   MEDIUM_LIST: '/notivix/notification-setting/medium/list',
//   DATASOURCE_API_LIST: '/common/dataSource/list',
//   FREQUENCY_LIST: 'notivix/notification-setting/frequency/list',
//   FREQUENCY_DETAIL: 'notivix/notification-setting/frequency',
//   NOTIFICATION_SETTING_TYPE_DETAIL: '/notivix/notification-setting/type',
//   GET_DATA_SOURCE_VERSION_BY_ID: '/common/dataSourceVersion/',
//   VALIDATION_ERROR_LIST: '/common/dataImportError/list',
//   GET_VERSION_DATA_BY_ID: '/common/dataSource/dataSourceDetails/',
//   NOTIFICATION_LOG_LIST:"/notivix/notification-setting/prepared/notification/list"
// };

export const POST = {
  LOGIN: "common/auth/login",
  USER_UPDATE: "/users/update",
  HELP_DESK_SUPPORT: "/support/create",
  CHANGE_PASSWORD: "/users/change-password",
  SEND_OTP: "common/auth/send-otp",
  VERIFY_OTP: "common/auth/verify-otp",
  CREATE_DASHBOARD: "/common/dashboard/create",
  UPDATE_DASHBOARD: "/common/dashboard/update",
  DELETE_DASHBOARD: "/common/dashboard/delete",
  CREATE_WIDGET: "/common/dashboard/widget/create",
  UPDATE_WIDGET: "/common/dashboard/widget/update",
  DELETE_WIDGET: "/common/dashboard/widget/delete",
  SAVE_WIDGETS: "/common/dashboard/widget/save",
  CREATE_USER: "common/auth/create-user",
  UPDATE_USER: "/common/users/update/",
  DELETE_USER: "/common/users/delete/",
  ORGANIZATION_ACTIVE: "/organizations/updateStatus/",
  USER_ACTIVE: "/users/updateStatus/",
  FILE_UPLOAD: "/common/files/upload",
  CREATE_ENTITY: "/common/entities/create",
  UPDATE_ENTITY: "/common/entities/update",
  CREATE_ATTRIBUTE_OPTION: "/common/attributeOptions/create",
  CREATE_DATA_SOURCE: "/common/dataSource/create",
  Custom_Report: "/customReports",
  DATA_SOURCE_VERSION_CREATE: "/common/dataSourceVersion/create",
  CREATE_THEME: "/common/widgetTheme/create",
  DELETE_THEME: "/widgetTheme/delete/",
  DUPLICATE_THEME: "/widgetTheme/duplicate/",
  UPDATE_THEME: "/widgetTheme/update/",
  UPDATE_REPORT_SETTINGS: "/customReports/updateSettings",
  Create_Organization: "/common/organization/create",
  Create_User: "/common/user/create",
  CREATE_PERMISSION: "/common/permission/create",
  CREATE_ROLE: "/common/role/create",
  CREATE_NOTIVIX_DASHBOARD: "/common/dashboard/create",
  UPDATE_NOTIVIX_DASHBOARD: "/common/dashboard/update",
  DELETE_NOTIVIX_DASHBOARD: "/common/dashboard/delete",
  NOTIVIX_DASHBOARD_WIDGET: "/dashboard/widget",
  NOTIVIX_DASHBOARD_THEME: "/dashboard/theme",
  OPERATOR_LIST: "/common/operator/list",
  CREATE_NOTIFICATION_TYPE: "/notivix/notification-setting/type/create",
  CREATE_FREQUENCY: "/notivix/notification-setting/frequency/create",
  CREATE_MEDIUM: "/notivix/notification-setting/medium/create",
  CREATE_VERSION_ROW: "/common/dataSourceVersion/versionData/create",
  RESOLVE_DATA_IMPORT_ERROR: "/common/dataImportError/resolve",
  TRIGGER_NOTIFICATION: "/notivix/notification-setting/prepared/trigger",
  CREATE_DESIGNATION: "/common/designation/create",
  CREATE_DEPARTMENT: "/common/department/create",
  CREATE_TEMPLATE: "/notivix/notification-setting/template/create",
    NOTIFICATION_SUMMARY: "notivix/notification-setting/type/summary",

};

export const PUT = {
  UPDATE_DATA_SOURCE: "/common/dataSource/update",
  UPDATE_ATTRIBUTE_OPTION: "/common/attributeOptions/update",
  UPDATE_ORGANIZATION: "/common/organization/update/",
  UPDATE_USER: "/common/user/update/",
  UPDATE_PERMISSION: "/common/permission/update",
  UPDATE_ROLE: "/common/role/update",
  UPDATE_MEDIUM: "/notivix/notification-setting/medium/update",
  UPDATE_FREQUENCY: "notivix/notification-setting/frequency/update",
  UPDATE_NOTIFICATION_TYPE: "notivix/notification-setting/type/update",
  UPDATE_VERSION_ROW: "/common/dataSourceVersion/versionData/update",
  SEND_ACKNOWLEDGE: "/notification-acknowledge/sendAcknowledge",
  CHANGE_PASSWORD: "/common/user/change-password",
  UPDATE_CURRENT_USER: "/common/user/update-current-user",
  UPDATE_DESIGNATION: "/common/designation/update",
  UPDATE_DEPARTMENT: "/common/department/update",
  UPDATE_TEMPLATE: "/notivix/notification-setting/template/update",
};

export const DELETE = {
  Delete_Organization: "/common/organization/delete",
  Delete_User: "/common/user/delete",
  DELETE_PERMISSION: "/common/permission/delete",
  DELETE_ROLE: "/common/role/delete",
  DELETE_NOTIFICATION_TYPE: "notivix/notification-setting/type/delete",
  DELETE_MEDIUM: "/notivix/notification-setting/medium/delete",
  DELETE_FREQUENCY: "/notivix/notification-setting/frequency/delete",
  DELETE_VERSION_ROW: "/common/dataSourceVersion/versionData/delete",
  DELETE_USER_IMAGE: "/common/user/image",
  DELETE_TEMPLATE: "/notivix/notification-setting/template/delete",
};

export const GET = {
  USER_DETAILS: "/common/user/get-current-user",
  USER_LIST: "/common/users/list",
  GET_USER: "/common/users/",
  GET_ORGANIZATION: "/organizations/",
  Entity_List: "/common/entities/list",
  Get_Entity: "/common/entities",
  Get_Entity_By_Id: "common/entities",
  Attribute_Option_List: "/common/attributeOptions/list",
  Attribute_Option_Get: "/common/attributeOptions/get",
  Data_Source_List: "/common/dataSource/list",
  Data_Source_Code: "/common/dataSource/code",
  Data_Source_Version: "/common/dataSourceVersion",
  Data_Source: "/common/dataSource/dataSourceId",
  Data_Source_Name: "/common/dataSource/name",
  Data_Import_Error: "/common/dataImportError",
  Custom_Report: "/reportivix/customReports",
  DATA_SOURCE_LIST: "/common/dataSource/list",
  ATTRIBUTE_OPTIONS_LIST: "/common/attributeOptions/get/",
  SOURCE_VERSION_DATA: "common/dataSourceVersion/versionData",
  DASHBOARD_LIST: "/common/dashboard/list",
  WIDGET_TYPE_LIST: "/common/widgetType/list",
  DASHBOARD_WIDGET_GET_CHART_DATA: "/common/dashboard/widget/getWidgets",
  DASHBOARD_WIDGET: "/dashboard/widget",
  DASHBOARD_WIDGET_DATA: "/common/dashboard/widget/getWidgetData",
  FIXED_DASHBOARD_WIDGET_DATA: "/common/dataSourceVersion/chartData",
  OPERATOR_LIST: "/common/operator/list",
  WIDGET_THEME: "/common/widgetTheme",
  NL_Query: "/nlQuery",
  NL_Query_INSIGHTS: "/nlQuery/insights",
  Report_Settings: "/common/customReports/listSettings?paginate=true",
  Organization_List: "/common/organization/list",
  Product_List: "/common/product/list",
  Product_Subscription_List: "/common/product-subscription/list",
  User_List: "/common/user/list",
  Roles_List: "/common/role/list",
  PERMISSION_LIST: "/common/permission/list",
  ROLE_LIST: "/common/role/list",
  ROLE_DETAIL: "/common/role",
  NOTIVIX_DASHBOARD_LIST: "/common/dashboard/list",
  NOTIVIX_DASHBOARD_WIDGET_GET_CHART_DATA:
    "/common/dashboard/widget/getWidgets",
  NOTIVIX_DASHBOARD_WIDGET_DATA: "/common/dashboard/widget/getWidgetData",
  NOTIFICATION_TYPE_LIST: "/notivix/notification-setting/type/list",
  TEMPLATE_LIST: "/notivix/notification-setting/template/list",
  MEDIUM_LIST: "/notivix/notification-setting/medium/list",
  DATASOURCE_API_LIST: "/common/dataSource/list",
  FREQUENCY_LIST: "notivix/notification-setting/frequency/list",
  FREQUENCY_DETAIL: "notivix/notification-setting/frequency",
  NOTIFICATION_SETTING_TYPE_DETAIL: "/notivix/notification-setting/type",
  GET_DATA_SOURCE_VERSION_BY_ID: "/common/dataSourceVersion/",
  VALIDATION_ERROR_LIST: "/common/dataImportError/list",
  GET_VERSION_DATA_BY_ID: "/common/dataSource/dataSourceDetails/",
  NOTIFICATION_LOG_LIST:
    "/notivix/notification-setting/prepared/notification/list",
  DEPARTMENT_LIST: "/common/department/list",
  DESIGNATION_LIST: "/common/designation/list",
  ERROR_ROW_DATA: "/common/dataImportError/data",
};
