'use client';
import React, { useMemo } from 'react';
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Box } from '@mui/material';
import { styled } from '@mui/material/styles';

// Import the sections and data from the provided file
const sections = [
  {
    sectionName: '',
    sectionBackGroundColor: '',
    sectionColor: '',
    sectionHorizontalAlignment: '',
    sectionVerticalAlignment: '',
    spanColumns: false,
    subSections: [
      {
        headerName: 'SBU',
        headerBackGroundColor: '7b7b7b',
        headerColor: 'ffffff',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'string',
        spanColumns: false,
      },
    ],
  },
  {
    sectionName: 'First Filings',
    sectionBackGroundColor: 'ffc000',
    sectionColor: '000000',
    sectionHorizontalAlignment: 'center',
    sectionVerticalAlignment: 'center',
    spanColumns: true,
    subSections: [
      {
        headerName: '2025 New Apps Filed',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '% of 2025 Invention Disclosures converted to Filings',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'percentage',
        spanColumns: false,
      },
      {
        headerName: '2025 New Apps Estimate',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2024 New Apps filed',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2023 New Apps filed',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2022 New Apps filed',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2021 New Apps filed',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
    ],
  },
  {
    sectionName: 'Disclosures',
    sectionBackGroundColor: 'ffc000',
    sectionColor: '000000',
    sectionHorizontalAlignment: 'center',
    sectionVerticalAlignment: 'center',
    spanColumns: true,
    subSections: [
      {
        headerName: 'Apps Being Drafted',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Projects Opened in 2025',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Projects Opened in 2024',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Projects Opened in 2023',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Projects Opened in 2022',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Projects Opened in 2021',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total Active Projects',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
    ],
  },
  {
    sectionName: '2025 Issued',
    sectionBackGroundColor: 'ffc000',
    sectionColor: '000000',
    sectionHorizontalAlignment: 'center',
    sectionVerticalAlignment: 'center',
    subSections: [
      {
        headerName: '2025 US Issued',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2025 Intl Issued',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
    ],
  },
  {
    sectionName: 'Pending Applications',
    sectionBackGroundColor: 'ffc000',
    sectionColor: '000000',
    sectionHorizontalAlignment: 'center',
    sectionVerticalAlignment: 'center',
    spanColumns: true,
    subSections: [
      {
        headerName: 'Total US Apps pending',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total EP Apps pending',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total CN Apps pending',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Other Country Apps pending',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total Apps pending',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
    ],
  },
  {
    sectionName: 'Issued Patents',
    sectionBackGroundColor: 'ffc000',
    sectionColor: '000000',
    sectionHorizontalAlignment: 'center',
    sectionVerticalAlignment: 'center',
    spanColumns: false,
    subSections: [
      {
        headerName: 'Total US Issued',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total EP Issued',
        headerBackGroundColor: 'b6c6e8',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total CN Issued',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Other Country Issued',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total Issued',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total Portfolio: Apps Pending+ Issued',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '% of Total Portfolio',
        headerBackGroundColor: '000000',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'percentage',
        spanColumns: false,
      },
    ],
  },
  {
    sectionName: '2025 Renewals Due',
    sectionBackGroundColor: 'ffc000',
    sectionColor: '000000',
    sectionHorizontalAlignment: 'center',
    sectionVerticalAlignment: 'center',
    spanColumns: false,
    subSections: [
      {
        headerName: '2025 Renewals Due',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
    ],
  },
  {
    sectionName: 'Reductions & Cost Savings',
    sectionBackGroundColor: 'ffc000',
    sectionColor: '000000',
    sectionHorizontalAlignment: 'center',
    sectionVerticalAlignment: 'center',
    spanColumns: false,
    subSections: [
      {
        headerName: 'Total No. of 2025** Reductions (Including reductions during prosecution)',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2025 Annuity Savings from 2025 reductions',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2026 Annuity Savings from 2025 reductions',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: '2025-2026 Annuity Savings from 2025 reductions',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'No. of Prosecution reductions in 2025',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Prosecution cost Savings',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
      {
        headerName: 'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions',
        headerBackGroundColor: 'ffffff',
        headerColor: '000000',
        horizontalAlignment: 'left',
        verticalAlignment: 'center',
        type: 'number',
        spanColumns: false,
      },
    ],
  },
];

const reportData = [
  {
    SBU: 'Metals',
    'First Filings': 0,
    '2025 New Apps Filed': 0,
    '% of 2025 Invention Disclosures converted to Filings': 0,
    '2025 New Apps Estimate': 2,
    '2024 New Apps filed': 2,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 0,
    'Projects Opened in 2025': 0,
    'Projects Opened in 2024': 2,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 11,
    '2025 Issued': 0,
    '2025 US Issued': 1,
    '2025 Intl Issued': 0,
    'Pending Applications': 0,
    'Total US Apps pending': 2,
    'Total EP Apps pending': 5,
    'Total CN Apps pending': 8,
    'Other Country Apps pending': 12,
    'Total Apps pending': 27,
    'Issued Patents': 0,
    'Total US Issued': 12,
    'Total EP Issued': 15,
    'Total CN Issued': 4,
    'Other Country Issued': 13,
    'Total Issued': 44,
    'Total Portfolio: Apps Pending+ Issued': 71,
    '% of Total Portfolio': 0.006203582350371341,
    '2025 Renewals Due': 46238,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 0,
    '2025 Annuity Savings from 2025 reductions': 0,
    '2026 Annuity Savings from 2025 reductions': 0,
    '2025-2026 Annuity Savings from 2025 reductions': 0,
    'No. of Prosecution reductions in 2025': 0,
    'Prosecution cost Savings': 0,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 0,
  },
  {
    SBU: 'Agri-Nutrients',
    'First Filings': 0,
    '2025 New Apps Filed': 1,
    '% of 2025 Invention Disclosures converted to Filings': 0.5,
    '2025 New Apps Estimate': 3,
    '2024 New Apps filed': 3,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 4,
    'Projects Opened in 2025': 2,
    'Projects Opened in 2024': 3,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 11,
    '2025 Issued': 0,
    '2025 US Issued': 1,
    '2025 Intl Issued': 2,
    'Pending Applications': 0,
    'Total US Apps pending': 37,
    'Total EP Apps pending': 62,
    'Total CN Apps pending': 32,
    'Other Country Apps pending': 203,
    'Total Apps pending': 334,
    'Issued Patents': 0,
    'Total US Issued': 36,
    'Total EP Issued': 19,
    'Total CN Issued': 16,
    'Other Country Issued': 91,
    'Total Issued': 162,
    'Total Portfolio: Apps Pending+ Issued': 496,
    '% of Total Portfolio': 0.043337702053298385,
    '2025 Renewals Due': 197266,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 2,
    '2025 Annuity Savings from 2025 reductions': 972,
    '2026 Annuity Savings from 2025 reductions': 0,
    '2025-2026 Annuity Savings from 2025 reductions': 972,
    'No. of Prosecution reductions in 2025': 2,
    'Prosecution cost Savings': 18765.11,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 19737.11,
  },
  {
    SBU: 'Chemicals',
    'First Filings': 0,
    '2025 New Apps Filed': 3,
    '% of 2025 Invention Disclosures converted to Filings': 0,
    '2025 New Apps Estimate': 4,
    '2024 New Apps filed': 4,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 15,
    'Projects Opened in 2025': 8,
    'Projects Opened in 2024': 4,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 65,
    '2025 Issued': 0,
    '2025 US Issued': 6,
    '2025 Intl Issued': 17,
    'Pending Applications': 0,
    'Total US Apps pending': 111,
    'Total EP Apps pending': 216,
    'Total CN Apps pending': 161,
    'Other Country Apps pending': 600,
    'Total Apps pending': 1088,
    'Issued Patents': 0,
    'Total US Issued': 288,
    'Total EP Issued': 560,
    'Total CN Issued': 182,
    'Other Country Issued': 628,
    'Total Issued': 1658,
    'Total Portfolio: Apps Pending+ Issued': 2746,
    '% of Total Portfolio': 0.23993010048055918,
    '2025 Renewals Due': 1315701.03,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 21,
    '2025 Annuity Savings from 2025 reductions': 23724,
    '2026 Annuity Savings from 2025 reductions': 12716,
    '2025-2026 Annuity Savings from 2025 reductions': 36440,
    'No. of Prosecution reductions in 2025': 2,
    'Prosecution cost Savings': 6226.23,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 42666.229999999996,
  },
  {
    SBU: 'Polymers',
    'First Filings': 0,
    '2025 New Apps Filed': 3,
    '% of 2025 Invention Disclosures converted to Filings': 0.07692307692307693,
    '2025 New Apps Estimate': 0,
    '2024 New Apps filed': 5,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 8,
    'Projects Opened in 2025': 13,
    'Projects Opened in 2024': 5,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 199,
    '2025 Issued': 0,
    '2025 US Issued': 13,
    '2025 Intl Issued': 54,
    'Pending Applications': 0,
    'Total US Apps pending': 223,
    'Total EP Apps pending': 362,
    'Total CN Apps pending': 222,
    'Other Country Apps pending': 410,
    'Total Apps pending': 1217,
    'Issued Patents': 0,
    'Total US Issued': 595,
    'Total EP Issued': 1541,
    'Total CN Issued': 525,
    'Other Country Issued': 682,
    'Total Issued': 3343,
    'Total Portfolio: Apps Pending+ Issued': 4560,
    '% of Total Portfolio': 0.3984272608125819,
    '2025 Renewals Due': 1929590,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 101,
    '2025 Annuity Savings from 2025 reductions': 118682,
    '2026 Annuity Savings from 2025 reductions': 76477,
    '2025-2026 Annuity Savings from 2025 reductions': 195159,
    'No. of Prosecution reductions in 2025': 12,
    'Prosecution cost Savings': 36687,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 231846,
  },
  {
    SBU: 'Specialties',
    'First Filings': 0,
    '2025 New Apps Filed': 3,
    '% of 2025 Invention Disclosures converted to Filings': 0,
    '2025 New Apps Estimate': 0,
    '2024 New Apps filed': 6,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 20,
    'Projects Opened in 2025': 13,
    'Projects Opened in 2024': 6,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 101,
    '2025 Issued': 0,
    '2025 US Issued': 6,
    '2025 Intl Issued': 46,
    'Pending Applications': 0,
    'Total US Apps pending': 147,
    'Total EP Apps pending': 230,
    'Total CN Apps pending': 136,
    'Other Country Apps pending': 186,
    'Total Apps pending': 699,
    'Issued Patents': 0,
    'Total US Issued': 633,
    'Total EP Issued': 620,
    'Total CN Issued': 392,
    'Other Country Issued': 315,
    'Total Issued': 1960,
    'Total Portfolio: Apps Pending+ Issued': 2659,
    '% of Total Portfolio': 0.23232852774137178,
    '2025 Renewals Due': 1302925.31,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 136,
    '2025 Annuity Savings from 2025 reductions': 0,
    '2026 Annuity Savings from 2025 reductions': 0,
    '2025-2026 Annuity Savings from 2025 reductions': 0,
    'No. of Prosecution reductions in 2025': 8,
    'Prosecution cost Savings': 28252.64,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 28252.64,
  },
  {
    SBU: 'Strategy & Transformation',
    'First Filings': 0,
    '2025 New Apps Filed': 0,
    '% of 2025 Invention Disclosures converted to Filings': 0,
    '2025 New Apps Estimate': 0,
    '2024 New Apps filed': 7,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 0,
    'Projects Opened in 2025': 0,
    'Projects Opened in 2024': 7,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 5,
    '2025 Issued': 0,
    '2025 US Issued': 0,
    '2025 Intl Issued': 0,
    'Pending Applications': 0,
    'Total US Apps pending': 1,
    'Total EP Apps pending': 2,
    'Total CN Apps pending': 1,
    'Other Country Apps pending': 6,
    'Total Apps pending': 10,
    'Issued Patents': 0,
    'Total US Issued': 0,
    'Total EP Issued': 0,
    'Total CN Issued': 0,
    'Other Country Issued': 0,
    'Total Issued': 0,
    'Total Portfolio: Apps Pending+ Issued': 10,
    '% of Total Portfolio': 0.0008737439930100481,
    '2025 Renewals Due': 0,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 0,
    '2025 Annuity Savings from 2025 reductions': 0,
    '2026 Annuity Savings from 2025 reductions': 0,
    '2025-2026 Annuity Savings from 2025 reductions': 0,
    'No. of Prosecution reductions in 2025': 0,
    'Prosecution cost Savings': 0,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 0,
  },
  {
    SBU: 'Scientific Design',
    'First Filings': 0,
    '2025 New Apps Filed': 0,
    '% of 2025 Invention Disclosures converted to Filings': 0,
    '2025 New Apps Estimate': 8,
    '2024 New Apps filed': 8,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 0,
    'Projects Opened in 2025': 0,
    'Projects Opened in 2024': 8,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 0,
    '2025 Issued': 0,
    '2025 US Issued': 0,
    '2025 Intl Issued': 0,
    'Pending Applications': 0,
    'Total US Apps pending': 0,
    'Total EP Apps pending': 0,
    'Total CN Apps pending': 0,
    'Other Country Apps pending': 0,
    'Total Apps pending': 109,
    'Issued Patents': 0,
    'Total US Issued': 0,
    'Total EP Issued': 0,
    'Total CN Issued': 0,
    'Other Country Issued': 0,
    'Total Issued': 263,
    'Total Portfolio: Apps Pending+ Issued': 372,
    '% of Total Portfolio': 0.032503276539973786,
    '2025 Renewals Due': 0,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 0,
    '2025 Annuity Savings from 2025 reductions': 0,
    '2026 Annuity Savings from 2025 reductions': 0,
    '2025-2026 Annuity Savings from 2025 reductions': 0,
    'No. of Prosecution reductions in 2025': 0,
    'Prosecution cost Savings': 0,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 0,
  },
  {
    SBU: 'Totals',
    'First Filings': 0,
    '2025 New Apps Filed': 14,
    '% of 2025 Invention Disclosures converted to Filings': 0.05555555555555555,
    '2025 New Apps Estimate': 18,
    '2024 New Apps filed': 36,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 48,
    'Projects Opened in 2025': 36,
    'Projects Opened in 2024': 36,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 437,
    '2025 Issued': 0,
    '2025 US Issued': 29,
    '2025 Intl Issued': 133,
    'Pending Applications': 0,
    'Total US Apps pending': 583,
    'Total EP Apps pending': 969,
    'Total CN Apps pending': 608,
    'Other Country Apps pending': 1594,
    'Total Apps pending': 3863,
    'Issued Patents': 0,
    'Total US Issued': 1615,
    'Total EP Issued': 2807,
    'Total CN Issued': 1139,
    'Other Country Issued': 1758,
    'Total Issued': 7582,
    'Total Portfolio: Apps Pending+ Issued': 11445,
    '% of Total Portfolio': 1,
    '2025 Renewals Due': 4949668.34,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 260,
    '2025 Annuity Savings from 2025 reductions': 143378,
    '2026 Annuity Savings from 2025 reductions': 89193,
    '2025-2026 Annuity Savings from 2025 reductions': 232571,
    'No. of Prosecution reductions in 2025': 24,
    'Prosecution cost Savings': 89930.98,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 322501.98,
  },
  {
    SBU: 'Corp T&I',
    'First Filings': 0,
    '2025 New Apps Filed': 4,
    '% of 2025 Invention Disclosures converted to Filings': 0,
    '2025 New Apps Estimate': 1,
    '2024 New Apps filed': 1,
    '2023 New Apps filed': 0,
    '2022 New Apps filed': 0,
    '2021 New Apps filed': 0,
    Disclosures: 0,
    'Apps Being Drafted': 1,
    'Projects Opened in 2025': 0,
    'Projects Opened in 2024': 1,
    'Projects Opened in 2023': 0,
    'Projects Opened in 2022': 0,
    'Projects Opened in 2021': 0,
    'Total Active Projects': 45,
    '2025 Issued': 0,
    '2025 US Issued': 2,
    '2025 Intl Issued': 14,
    'Pending Applications': 0,
    'Total US Apps pending': 62,
    'Total EP Apps pending': 92,
    'Total CN Apps pending': 48,
    'Other Country Apps pending': 177,
    'Total Apps pending': 379,
    'Issued Patents': 0,
    'Total US Issued': 51,
    'Total EP Issued': 52,
    'Total CN Issued': 20,
    'Other Country Issued': 29,
    'Total Issued': 152,
    'Total Portfolio: Apps Pending+ Issued': 531,
    '% of Total Portfolio': 0.04639580602883355,
    '2025 Renewals Due': 157948,
    'Total No. of 2025** Reductions (Including reductions during prosecution)': 0,
    '2025 Annuity Savings from 2025 reductions': 0,
    '2026 Annuity Savings from 2025 reductions': 0,
    '2025-2026 Annuity Savings from 2025 reductions': 0,
    'No. of Prosecution reductions in 2025': 0,
    'Prosecution cost Savings': 0,
    'Total Cost Savings: (2025-2026) Annuity Savings + Prosecution savings from 2025 reductions': 0,
  },
];

// Styled components for custom table styling
const StyledTableContainer = styled(TableContainer)({
  maxWidth: '100%',
  overflowX: 'auto',
  border: '1px solid #ccc',
  boxShadow: 'none',
});

// Dynamic styled cell component that takes color props
const DynamicCell = styled(TableCell)<{
  bgColor?: string;
  textColor?: string;
  align?: 'left' | 'center' | 'right';
  fontWeight?: string;
}>(({ bgColor, textColor, align, fontWeight }) => ({
  backgroundColor: bgColor ? `#${bgColor}` : 'transparent',
  color: textColor ? `#${textColor}` : 'inherit',
  padding: '6px',
  textAlign: align || 'left',
  border: '1px solid #ccc',
  fontSize: '0.8rem',
  fontWeight: fontWeight || 'normal',
}));

// Format value based on type
const formatValue = ({ value, type }: { value: any; type: string }) => {
  if (value === undefined || value === null) return '';

  if (type === 'percentage') {
    return typeof value === 'number' ? `${(value * 100).toFixed(1)}%` : value;
  }

  if (type === 'number' && typeof value === 'number') {
    // Format currency values
    if (value >= 1000) {
      return `$ ${(value / 1000).toFixed(0)} K`;
    }
    return value.toString();
  }

  return value;
};

export default function ViewReport() {
  return (
    <Box sx={{ width: '100%' }}>
      <StyledTableContainer>
        <Table size="small" aria-label="patent portfolio table">
          <TableHead></TableHead>
          <TableBody>
            {sections.map((section, sectionIndex) => {
              return (
                <React.Fragment key={`section-${sectionIndex}`}>
                  {(section.sectionName || section.spanColumns) && (
                    <TableRow>
                      <DynamicCell
                        bgColor={section.sectionBackGroundColor}
                        textColor={section.sectionColor}
                        fontWeight="bold"
                        align="center"
                        colSpan={reportData.length + 1}
                      >
                        {section.sectionName}
                      </DynamicCell>
                    </TableRow>
                  )}
                  {section.subSections?.map((subSection, subIndex) => (
                    <TableRow key={`subsection-${sectionIndex}-${subIndex}`}>
                      <DynamicCell
                        bgColor={subSection.headerBackGroundColor}
                        textColor={subSection.headerColor}
                        fontWeight="bold"
                        align="center"
                      >
                        {subSection.headerName}
                      </DynamicCell>
                      {reportData.map((data: any, dataIndex) => (
                        <DynamicCell
                          bgColor={subSection.headerBackGroundColor}
                          textColor={subSection.headerColor}
                          fontWeight="bold"
                          align="center"
                        >
                          {formatValue({ value: data[subSection.headerName], type: subSection.type })}
                        </DynamicCell>
                      ))}
                    </TableRow>
                  ))}
                </React.Fragment>
              );
            })}
          </TableBody>
        </Table>
      </StyledTableContainer>
    </Box>
  );
}
