export const countryCodes = [
  { iso: "AF", dialCode: "+93", label: "Afghanistan (+93)" },
  { iso: "AL", dialCode: "+355", label: "Albania (+355)" },
  { iso: "DZ", dialCode: "+213", label: "Algeria (+213)" },
  { iso: "AD", dialCode: "+376", label: "Andorra (+376)" },
  { iso: "AO", dialCode: "+244", label: "Angola (+244)" },
  { iso: "AG", dialCode: "+1", label: "Antigua and Barbuda (+1)" },
  { iso: "AR", dialCode: "+54", label: "Argentina (+54)" },
  { iso: "AM", dialCode: "+374", label: "Armenia (+374)" },
  { iso: "AU", dialCode: "+61", label: "Australia (+61)" },
  { iso: "AT", dialCode: "+43", label: "Austria (+43)" },
  { iso: "AZ", dialCode: "+994", label: "Azerbaijan (+994)" },
  { iso: "BS", dialCode: "+1", label: "Bahamas (+1)" },
  { iso: "BH", dialCode: "+973", label: "Bahrain (+973)" },
  { iso: "BD", dialCode: "+880", label: "Bangladesh (+880)" },
  { iso: "BB", dialCode: "+1", label: "Barbados (+1)" },
  { iso: "BY", dialCode: "+375", label: "Belarus (+375)" },
  { iso: "BE", dialCode: "+32", label: "Belgium (+32)" },
  { iso: "BZ", dialCode: "+501", label: "Belize (+501)" },
  { iso: "BJ", dialCode: "+229", label: "Benin (+229)" },
  { iso: "BT", dialCode: "+975", label: "Bhutan (+975)" },
  { iso: "BO", dialCode: "+591", label: "Bolivia (+591)" },
  { iso: "BA", dialCode: "+387", label: "Bosnia and Herzegovina (+387)" },
  { iso: "BW", dialCode: "+267", label: "Botswana (+267)" },
  { iso: "BR", dialCode: "+55", label: "Brazil (+55)" },
  { iso: "BN", dialCode: "+673", label: "Brunei (+673)" },
  { iso: "BG", dialCode: "+359", label: "Bulgaria (+359)" },
  { iso: "BF", dialCode: "+226", label: "Burkina Faso (+226)" },
  { iso: "BI", dialCode: "+257", label: "Burundi (+257)" },
  { iso: "KH", dialCode: "+855", label: "Cambodia (+855)" },
  { iso: "CM", dialCode: "+237", label: "Cameroon (+237)" },
  { iso: "CA", dialCode: "+1", label: "Canada (+1)" },
  { iso: "CV", dialCode: "+238", label: "Cape Verde (+238)" },
  { iso: "CF", dialCode: "+236", label: "Central African Republic (+236)" },
  { iso: "TD", dialCode: "+235", label: "Chad (+235)" },
  { iso: "CL", dialCode: "+56", label: "Chile (+56)" },
  { iso: "CN", dialCode: "+86", label: "China (+86)" },
  { iso: "CO", dialCode: "+57", label: "Colombia (+57)" },
  { iso: "KM", dialCode: "+269", label: "Comoros (+269)" },
  { iso: "CG", dialCode: "+242", label: "Congo (+242)" },
  { iso: "CR", dialCode: "+506", label: "Costa Rica (+506)" },
  { iso: "HR", dialCode: "+385", label: "Croatia (+385)" },
  { iso: "CU", dialCode: "+53", label: "Cuba (+53)" },
  { iso: "CY", dialCode: "+357", label: "Cyprus (+357)" },
  { iso: "CZ", dialCode: "+420", label: "Czech Republic (+420)" },
  { iso: "DK", dialCode: "+45", label: "Denmark (+45)" },
  { iso: "DJ", dialCode: "+253", label: "Djibouti (+253)" },
  { iso: "DM", dialCode: "+1", label: "Dominica (+1)" },
  { iso: "DO", dialCode: "+1", label: "Dominican Republic (+1)" },
  { iso: "EC", dialCode: "+593", label: "Ecuador (+593)" },
  { iso: "EG", dialCode: "+20", label: "Egypt (+20)" },
  { iso: "SV", dialCode: "+503", label: "El Salvador (+503)" },
  { iso: "GQ", dialCode: "+240", label: "Equatorial Guinea (+240)" },
  { iso: "ER", dialCode: "+291", label: "Eritrea (+291)" },
  { iso: "EE", dialCode: "+372", label: "Estonia (+372)" },
  { iso: "ET", dialCode: "+251", label: "Ethiopia (+251)" },
  { iso: "FJ", dialCode: "+679", label: "Fiji (+679)" },
  { iso: "FI", dialCode: "+358", label: "Finland (+358)" },
  { iso: "FR", dialCode: "+33", label: "France (+33)" },
  { iso: "GA", dialCode: "+241", label: "Gabon (+241)" },
  { iso: "GM", dialCode: "+220", label: "Gambia (+220)" },
  { iso: "GE", dialCode: "+995", label: "Georgia (+995)" },
  { iso: "DE", dialCode: "+49", label: "Germany (+49)" },
  { iso: "GH", dialCode: "+233", label: "Ghana (+233)" },
  { iso: "GR", dialCode: "+30", label: "Greece (+30)" },
  { iso: "GD", dialCode: "+1", label: "Grenada (+1)" },
  { iso: "GT", dialCode: "+502", label: "Guatemala (+502)" },
  { iso: "GN", dialCode: "+224", label: "Guinea (+224)" },
  { iso: "GW", dialCode: "+245", label: "Guinea-Bissau (+245)" },
  { iso: "GY", dialCode: "+592", label: "Guyana (+592)" },
  { iso: "HT", dialCode: "+509", label: "Haiti (+509)" },
  { iso: "HN", dialCode: "+504", label: "Honduras (+504)" },
  { iso: "HU", dialCode: "+36", label: "Hungary (+36)" },
  { iso: "IS", dialCode: "+354", label: "Iceland (+354)" },
  { iso: "IN", dialCode: "+91", label: "India (+91)" },
  { iso: "ID", dialCode: "+62", label: "Indonesia (+62)" },
  { iso: "IR", dialCode: "+98", label: "Iran (+98)" },
  { iso: "IQ", dialCode: "+964", label: "Iraq (+964)" },
  { iso: "IE", dialCode: "+353", label: "Ireland (+353)" },
  { iso: "IL", dialCode: "+972", label: "Israel (+972)" },
  { iso: "IT", dialCode: "+39", label: "Italy (+39)" },
  { iso: "JM", dialCode: "+1", label: "Jamaica (+1)" },
  { iso: "JP", dialCode: "+81", label: "Japan (+81)" },
  { iso: "JO", dialCode: "+962", label: "Jordan (+962)" },
  { iso: "KZ", dialCode: "+7", label: "Kazakhstan (+7)" },
  { iso: "KE", dialCode: "+254", label: "Kenya (+254)" },
  { iso: "KI", dialCode: "+686", label: "Kiribati (+686)" },
  { iso: "KW", dialCode: "+965", label: "Kuwait (+965)" },
  { iso: "KG", dialCode: "+996", label: "Kyrgyzstan (+996)" },
  { iso: "LA", dialCode: "+856", label: "Laos (+856)" },
  { iso: "LV", dialCode: "+371", label: "Latvia (+371)" },
  { iso: "LB", dialCode: "+961", label: "Lebanon (+961)" },
  { iso: "LS", dialCode: "+266", label: "Lesotho (+266)" },
  { iso: "LR", dialCode: "+231", label: "Liberia (+231)" },
  { iso: "LY", dialCode: "+218", label: "Libya (+218)" },
  { iso: "LI", dialCode: "+423", label: "Liechtenstein (+423)" },
  { iso: "LT", dialCode: "+370", label: "Lithuania (+370)" },
  { iso: "LU", dialCode: "+352", label: "Luxembourg (+352)" },
  { iso: "MG", dialCode: "+261", label: "Madagascar (+261)" },
  { iso: "MW", dialCode: "+265", label: "Malawi (+265)" },
  { iso: "MY", dialCode: "+60", label: "Malaysia (+60)" },
  { iso: "MV", dialCode: "+960", label: "Maldives (+960)" },
  { iso: "ML", dialCode: "+223", label: "Mali (+223)" },
  { iso: "MT", dialCode: "+356", label: "Malta (+356)" },
  { iso: "MH", dialCode: "+692", label: "Marshall Islands (+692)" },
  { iso: "MR", dialCode: "+222", label: "Mauritania (+222)" },
  { iso: "MU", dialCode: "+230", label: "Mauritius (+230)" },
  { iso: "MX", dialCode: "+52", label: "Mexico (+52)" },
  { iso: "FM", dialCode: "+691", label: "Micronesia (+691)" },
  { iso: "MD", dialCode: "+373", label: "Moldova (+373)" },
  { iso: "MC", dialCode: "+377", label: "Monaco (+377)" },
  { iso: "MN", dialCode: "+976", label: "Mongolia (+976)" },
  { iso: "ME", dialCode: "+382", label: "Montenegro (+382)" },
  { iso: "MA", dialCode: "+212", label: "Morocco (+212)" },
  { iso: "MZ", dialCode: "+258", label: "Mozambique (+258)" },
  { iso: "MM", dialCode: "+95", label: "Myanmar (+95)" },
  { iso: "NA", dialCode: "+264", label: "Namibia (+264)" },
  { iso: "NR", dialCode: "+674", label: "Nauru (+674)" },
  { iso: "NP", dialCode: "+977", label: "Nepal (+977)" },
  { iso: "NL", dialCode: "+31", label: "Netherlands (+31)" },
  { iso: "NZ", dialCode: "+64", label: "New Zealand (+64)" },
  { iso: "NI", dialCode: "+505", label: "Nicaragua (+505)" },
  { iso: "NE", dialCode: "+227", label: "Niger (+227)" },
  { iso: "NG", dialCode: "+234", label: "Nigeria (+234)" },
  { iso: "NO", dialCode: "+47", label: "Norway (+47)" },
  { iso: "OM", dialCode: "+968", label: "Oman (+968)" },
  { iso: "PK", dialCode: "+92", label: "Pakistan (+92)" },
  { iso: "PW", dialCode: "+680", label: "Palau (+680)" },
  { iso: "PA", dialCode: "+507", label: "Panama (+507)" },
  { iso: "PG", dialCode: "+675", label: "Papua New Guinea (+675)" },
  { iso: "PY", dialCode: "+595", label: "Paraguay (+595)" },
  { iso: "PE", dialCode: "+51", label: "Peru (+51)" },
  { iso: "PH", dialCode: "+63", label: "Philippines (+63)" },
  { iso: "PL", dialCode: "+48", label: "Poland (+48)" },
  { iso: "PT", dialCode: "+351", label: "Portugal (+351)" },
  { iso: "QA", dialCode: "+974", label: "Qatar (+974)" },
  { iso: "RO", dialCode: "+40", label: "Romania (+40)" },
  { iso: "RU", dialCode: "+7", label: "Russia (+7)" },
  { iso: "RW", dialCode: "+250", label: "Rwanda (+250)" },
  { iso: "KN", dialCode: "+1", label: "Saint Kitts and Nevis (+1)" },
  { iso: "LC", dialCode: "+1", label: "Saint Lucia (+1)" },
  { iso: "VC", dialCode: "+1", label: "Saint Vincent and the Grenadines (+1)" },
  { iso: "WS", dialCode: "+685", label: "Samoa (+685)" },
  { iso: "SM", dialCode: "+378", label: "San Marino (+378)" },
  { iso: "ST", dialCode: "+239", label: "Sao Tome and Principe (+239)" },
  { iso: "SA", dialCode: "+966", label: "Saudi Arabia (+966)" },
  { iso: "SN", dialCode: "+221", label: "Senegal (+221)" },
  { iso: "RS", dialCode: "+381", label: "Serbia (+381)" },
  { iso: "SC", dialCode: "+248", label: "Seychelles (+248)" },
  { iso: "SL", dialCode: "+232", label: "Sierra Leone (+232)" },
  { iso: "SG", dialCode: "+65", label: "Singapore (+65)" },
  { iso: "SK", dialCode: "+421", label: "Slovakia (+421)" },
  { iso: "SI", dialCode: "+386", label: "Slovenia (+386)" },
  { iso: "SB", dialCode: "+677", label: "Solomon Islands (+677)" },
  { iso: "SO", dialCode: "+252", label: "Somalia (+252)" },
  { iso: "ZA", dialCode: "+27", label: "South Africa (+27)" },
  { iso: "KR", dialCode: "+82", label: "South Korea (+82)" },
  { iso: "ES", dialCode: "+34", label: "Spain (+34)" },
  { iso: "LK", dialCode: "+94", label: "Sri Lanka (+94)" },
  { iso: "SD", dialCode: "+249", label: "Sudan (+249)" },
  { iso: "SR", dialCode: "+597", label: "Suriname (+597)" },
  { iso: "SE", dialCode: "+46", label: "Sweden (+46)" },
  { iso: "CH", dialCode: "+41", label: "Switzerland (+41)" },
  { iso: "SY", dialCode: "+963", label: "Syria (+963)" },
  { iso: "TW", dialCode: "+886", label: "Taiwan (+886)" },
  { iso: "TJ", dialCode: "+992", label: "Tajikistan (+992)" },
  { iso: "TZ", dialCode: "+255", label: "Tanzania (+255)" },
  { iso: "TH", dialCode: "+66", label: "Thailand (+66)" },
  { iso: "TL", dialCode: "+670", label: "Timor-Leste (+670)" },
  { iso: "TG", dialCode: "+228", label: "Togo (+228)" },
  { iso: "TO", dialCode: "+676", label: "Tonga (+676)" },
  { iso: "TT", dialCode: "+1", label: "Trinidad and Tobago (+1)" },
  { iso: "TN", dialCode: "+216", label: "Tunisia (+216)" },
  { iso: "TR", dialCode: "+90", label: "Turkey (+90)" },
  { iso: "TM", dialCode: "+993", label: "Turkmenistan (+993)" },
  { iso: "TV", dialCode: "+688", label: "Tuvalu (+688)" },
  { iso: "UG", dialCode: "+256", label: "Uganda (+256)" },
  { iso: "UA", dialCode: "+380", label: "Ukraine (+380)" },
  { iso: "AE", dialCode: "+971", label: "United Arab Emirates (+971)" },
  { iso: "GB", dialCode: "+44", label: "United Kingdom (+44)" },
  { iso: "US", dialCode: "+1", label: "United States (+1)" },
  { iso: "UY", dialCode: "+598", label: "Uruguay (+598)" },
  { iso: "UZ", dialCode: "+998", label: "Uzbekistan (+998)" },
  { iso: "VU", dialCode: "+678", label: "Vanuatu (+678)" },
  { iso: "VA", dialCode: "+379", label: "Vatican City (+379)" },
  { iso: "VE", dialCode: "+58", label: "Venezuela (+58)" },
  { iso: "VN", dialCode: "+84", label: "Vietnam (+84)" },
  { iso: "YE", dialCode: "+967", label: "Yemen (+967)" },
  { iso: "ZM", dialCode: "+260", label: "Zambia (+260)" },
  { iso: "ZW", dialCode: "+263", label: "Zimbabwe (+263)" }
];