export const CURRENCIES = [
  { code: "USD", label: "USD - US Dollar" },
  { code: "EUR", label: "EUR - Euro" },
  { code: "GBP", label: "GBP - British Pound Sterling" },
  { code: "INR", label: "INR - Indian Rupee" },
  { code: "AUD", label: "AUD - Australian Dollar" },
  { code: "CAD", label: "CAD - Canadian Dollar" },
  { code: "CHF", label: "CHF - Swiss Franc" },
  { code: "CNY", label: "CNY - Chinese Yuan" },
  { code: "JPY", label: "JPY - Japanese Yen" },
  { code: "NZD", label: "NZD - New Zealand Dollar" },
  { code: "SGD", label: "SGD - Singapore Dollar" },
  { code: "HKD", label: "HKD - Hong Kong Dollar" },
  { code: "SEK", label: "SEK - Swedish Krona" },
  { code: "NOK", label: "NOK - Norwegian Krone" },
  { code: "DKK", label: "DKK - Danish Krone" },
  { code: "ZAR", label: "ZAR - South African Rand" },
  { code: "AED", label: "AED - UAE Dirham" },
  { code: "SAR", label: "SAR - Saudi Riyal" },
  { code: "BRL", label: "BRL - Brazilian Real" },
  { code: "MXN", label: "MXN - Mexican Peso" },
  { code: "RUB", label: "RUB - Russian Ruble" },
  { code: "KRW", label: "KRW - South Korean Won" },
  { code: "TRY", label: "TRY - Turkish Lira" },
  { code: "IDR", label: "IDR - Indonesian Rupiah" },
  { code: "MYR", label: "MYR - Malaysian Ringgit" },
  { code: "THB", label: "THB - Thai Baht" },
  { code: "PHP", label: "PHP - Philippine Peso" },
  { code: "PLN", label: "PLN - Polish Zloty" },
  { code: "CZK", label: "CZK - Czech Koruna" },
  { code: "HUF", label: "HUF - Hungarian Forint" },
  { code: "ILS", label: "ILS - Israeli Shekel" },
  { code: "EGP", label: "EGP - Egyptian Pound" },
  { code: "PKR", label: "PKR - Pakistani Rupee" },
  { code: "BDT", label: "BDT - Bangladeshi Taka" },
  { code: "LKR", label: "LKR - Sri Lankan Rupee" },
  { code: "NGN", label: "NGN - Nigerian Naira" },
  { code: "KES", label: "KES - Kenyan Shilling" },
  { code: "GHS", label: "GHS - Ghanaian Cedi" },
  { code: "ARS", label: "ARS - Argentine Peso" },
  { code: "CLP", label: "CLP - Chilean Peso" },
  { code: "COP", label: "COP - Colombian Peso" },
  { code: "VND", label: "VND - Vietnamese Dong" }
];